import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./scss/style.scss";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "일정관리",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' no-scroll-bar'}>
        <SessionProvider
          session={undefined}
          refetchOnWindowFocus={false}>
          {children}
        </SessionProvider>
        <script type="text/javascript" src="https://dapi.kakao.com/v2/maps/sdk.js?appkey=18e5eed79170a888a460e63b085421a3&libraries=services"></script>
      </body>
    </html>
  );
}
