import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./scss/style.scss";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "일정관리",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' no-scroll-bar'}>
        <SessionProvider session={undefined} >
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
